name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]

jobs:
  some-name:

    runs-on: some-os

    defaults:
      run:
        working-directory: ./example-app

    steps:
      ...
